[package]
name = "solution_4"
version = "0.0.1"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
flash = { local = "./movectf-4" }

[addresses]
sui =  "0000000000000000000000000000000000000002"
